#!/usr/bin/env python3

import sys
import dns.resolver 

if len(sys.argv) > 2:
	rec_type = str.upper(sys.argv[2])
	if len(sys.argv) > 3:
		rec_type2 = str.upper(sys.argv[3])
owner = str(sys.argv[1])
owners = open("/etc/trueuserowners", "r")
owners_list = owners.read().splitlines()

owner_match = []

for split in owners_list:
	split = split.split(": ")
	if owner in split[1]:
		owner_match.append(split[0])


domains = open("/etc/userdomains", "r")
domain_list = domains.read().splitlines()

domain_match = []

for user in owner_match:
	for domain in domain_list:
		d_split  = domain.split(": ")
		if user in d_split[1]:
			domain_match.append(d_split[0])


if len(sys.argv) > 2: 
	for domain in domain_match:
		print(domain)
		try:
			result = dns.resolver.query(domain, rec_type)
			for answer in result:
				print("\t", answer.to_text())
		except:
			pass
			print("That's a nope on the ", rec_type, " record there, bud.")
		if len(sys.argv) > 3:
			try:
				result2 = dns.resolver.query(domain, rec_type2)
				for answer2 in result2:
					print("\t" + answer2.to_text())
			except:
				pass
				print("that's a nope on the " + rec_type2 + " record there, bud.")
else:
	for domain in domain_match:
		print(domain) 
